# ------------------------------------------------------------
# グローバル設定
# ------------------------------------------------------------
globals:
  logging:
    level: "DEBUG" # DEBUG, INFO, WARNING, ERROR, CRITICAL

services:
  lfo_engine:
    fps: 60
  led_renderer:
    max_brightness: 10

controller:
  long_press_duration: 0.2 # 長押しと判定するまでの時間（秒）

mode:
  preset_select_mode:
    threshold: 100

senders:
  midi:
    enabled: false # MIDI送信を有効にする
    port_name: "ArcController OUT" # MIDI出力ポート名
    channel: 1 # MIDIチャンネル
    cc_base: 0 # MIDI CCのベース番号

# ------------------------------------------------------------
# モデル設定
# ------------------------------------------------------------
model:
  # 使用するレイヤー数
  num_layers: 4

# ------------------------------------------------------------
# プリセット定義
# ------------------------------------------------------------
presets:
  - name: potentiometer
    value_style: midi_14_bit # linear, infinite, bipolar, midi_7_bit, midi_14_bit
    led_style: potentiometer
    lfo_style: static
  - name: dot
    value_style: midi_14_bit
    led_style: dot
    lfo_style: static
  - name: bipolar
    value_style: midi_14_bit
    led_style: bipolar
    lfo_style: static
  - name: dot
    value_style: midi_14_bit
    led_style: dot
    lfo_style: random_ease
  - name: perlin
    value_style: midi_14_bit
    led_style: perlin
    lfo_style: perlin
