# ------------------------------------------------------------
# グローバル設定
# ------------------------------------------------------------
globals:
  # ログレベル（main.py の setup_logging に渡す）
  logging:
    level: "INFO" # DEBUG, INFO, WARNING, ERROR, CRITICAL

component:
  lfo_engine:
    fps: 60
  led_renderer:
    max_brightness: 10

mode:
  preset_select_mode:
    threshold: 200

# ------------------------------------------------------------
# プリセット定義
# ------------------------------------------------------------
presets:
  - name: potentiometer
    value_style: linear
    led_style: potentiometer
    lfo_style: static
  - name: dot
    value_style: infinite
    led_style: dot
    lfo_style: static
  - name: bipolar
    value_style: bipolar
    led_style: bipolar
    lfo_style: static
  - name: perlin
    value_style: linear
    led_style: perlin
    lfo_style: perlin
