# ------------------------------------------------------------
# グローバル設定
# ------------------------------------------------------------
globals:
  # ログレベル（main.py の setup_logging に渡す）
  logging:
    level: "DEBUG" # DEBUG, INFO, WARNING, ERROR, CRITICAL

services:
  lfo_engine:
    fps: 60
  led_renderer:
    max_brightness: 10

mode:
  preset_select_mode:
    threshold: 100

# ------------------------------------------------------------
# モデル設定
# ------------------------------------------------------------
model:
  # 使用するレイヤー数
  num_layers: 4
# ------------------------------------------------------------
# プリセット定義
# ------------------------------------------------------------
presets:
  - name: potentiometer_midi
    value_style: midi_7_bit # linear, infinite, bipolar, midi_7_bit, midi_14_bit
    led_style: potentiometer
    lfo_style: static
  - name: potentiometer
    value_style: linear # linear, infinite, bipolar, midi_7_bit, midi_14_bit
    led_style: potentiometer
    lfo_style: static
  - name: dot
    value_style: infinite
    led_style: dot
    lfo_style: static
  - name: bipolar
    value_style: bipolar
    led_style: bipolar
    lfo_style: static
  - name: perlin
    value_style: linear
    led_style: perlin
    lfo_style: perlin
