# ------------------------------------------------------------
# グローバル設定
# ------------------------------------------------------------
globals:
  # ログレベル（main.py の setup_logging に渡す）
  logging:
    level: "WARNING"

  lfo_engine:
    fps: 60

  controller:
    value_gain: 0.001 # ringΔに対するvalueの増分
    lfo_freq_gain: 0.0005 # ringΔに対するlfo周波数の増分

  led_renderer:
    max_brightness: 10
